---
name: test

on: [push, pull_request]

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: yaml-lint
      uses: ibiqlik/action-yamllint@v3
      with:
        config_data: "{extends: default}"
        file_or_dir: ./*yml
  composecheck:
    runs-on: ubuntu-22.04
    steps:
      - name: compose check
        run:
          VOL_PREFIX=/tmp docker compose -f torchserve.yml config
          VOL_PREFIX=/tmp docker compose -f torchserve-cuda.yml config
          GAMUTRF=gamutrf VOL_PREFIX=/tmp docker compose -f waterfall.yml config
          TORCHSERVE=torchserve FREQ_START=5e9 FREQ_END=6e9 VOL_PREFIX=/tmp docker compose -f pi5-scanner-inference.yml config
          TORCHSERVE=torchserve FREQ_START=5e9 FREQ_END=6e9 VOL_PREFIX=/tmp docker compose -f scanner.yml -f waterfall.yml -f torchserve-cuda.yml config
