---
name: test

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: compose check
      run: |
        docker compose -f torchserve.yml config && \
        docker compose -f torchserve-cuda.yml config && \
        docker compose -f waterfall.yml config && \
        docker compose -f scanner.yml -f waterfall.yml -f torchserve-cuda.yml config && \
        docker compose -f offline.yml -f offline.yml config
